<div class="container-lg">
  <h1 class="mt-5 mb-3">Сайты</h1>
  <div class="table-responsive">
    <table class="table table-bordered table-hover text-nowrap" data-test="urls">
      <thead>
        <tr>
          <th>ID</th>
          <th>Имя</th>
          <th>Дата создания</th>
          <th>Код ответа</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($urls as $url): ?>
          <tr>
            <td><?= $url['id'] ?></td>
            <td><a href="/urls/<?= $url['id'] ?>"><?= $url['name'] ?></a></td>
            <td><?= $url['last_check'] ?? '' ?></td>
            <td><?= $url['status_code'] ?? '' ?></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
</div>