<div class="jumbotron jumbotron-fluid bg-light p-5 border rounded-3">
  <div class="ps-5 container">
    <h1 class="display-4">Анализатор страниц</h1>
    <p class="my-3 lead">Бесплатно проверяйте сайты на соответствие SEO</p>
    <form action="/urls" method="post" class="row g-3">
      <div class="col-8">
        <input type="text" name="url" class="form-control form-control-lg" placeholder="https://example.com">
      </div>
      <div class="col-4">
        <button type="submit" class="btn btn-primary btn-lg px-5 text-uppercase">Проверить</button>
      </div>
    </form>
  </div>
</div>